name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # setiap hari jam 00:00 UTC
  workflow_dispatch:      # bisa dijalankan manual juga

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set Git identity
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your@email.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/sapa-apps/SAPA-PROJECT.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || echo "No merge"
          git push origin main
